### PR TITLE
docs: clarify tailnet var

### LINKED ISSUE #206: Tailscale provider returns 403 when user tailnet does not match
One of the more common (I suspect) issues a new user of the provider may run into is that the tailnet name may not be correct. In this case the provider will return an error like this:

```
│ Error: Failed to create key
│
│   with module.my_module.tailscale_tailnet_key.default,
│   on ../modules/gcp_gitlab_runner/[main.tf](http://main.tf/) line 28, in resource "tailscale_tailnet_key" "default":
│   28: resource "tailscale_tailnet_key" "default" {
│
│ user tailnet does not match (403)
╵
```
I encountered this issue on the free tier and was able to resolve it by referring to the [API documentation](https://github.com/tailscale/tailscale/blob/main/api.md#tailnet). My tailnet name was the same as my organization name, i.e. equivalent to "example.com" in the API documentation. I'm not immediately sure how the tailnet name changes when you start paying for tailscale as the API docs are not all that clear.

I think that README.md could be updated to make this a little clearer.

### PR DESCRIPTION
**Pull request by santiagon610**
**What this PR does / why we need it**: This PR clarifies some of the documentation related to the `tailnet` provider variable. Since it took digging into the issues (see below for references) to find the appropriate value, this may help future users.

**Which issue this PR fixes**:

- Fixes #206 
- Mentions #207

### CODE REVIEW

**Review by whosthegoss — APPROVED** [review]

**Comment by whosthegoss** [comment]
LGTM

**Comment by santiagon610** [comment]
Thanks @davidsbond, since I don't have any insight into the CI jobs, I was able to perform the steps that you recommended. Since `tfplugindocs validate .` gave me an exit code of 0, I assume I _should_ be good now.

```
❯ tfplugindocs validate .
detected static docs directory, running checks
❯ echo $?
0
```

**Comment by davidsbond** [comment]
Yep that should be fine! Someone on the tailscale team should be able to run the CI here, approve & merge for you. I can't do that.

**Comment by bailey-ts** [comment]
Hey @DentonGentry, would it be possible to get a review on this?

**Review by knyar — APPROVED** [review]

**Pull request merged**
