### PR TITLE
Document that ACL tests are run when creating and updating tailscale_acl resources.

### LINKED ISSUE #158: allowing validating the ACL tests before `terraform apply`
We prefer to manage our infrastructure with Terraform whenever possible. But one nice feature that [Tailscale's GitOps Pusher](https://github.com/tailscale/tailscale/tree/main/cmd/gitops-pusher) supports is to validate your ACL logic pre-merge in a PR by asking Tailscale to run the ACL tests. It'd be great if the Terraform provider could support this somehow as well.

I'm not entirely sure how to best fit this into a Terraform workflow -- my first thought would be to have `terraform plan` run the validation step. But that would perhaps be surprising to some?

### PR DESCRIPTION
**Pull request by dsymonds**
Fixes #158.
Closes #161.

### CODE REVIEW

**Comment by dsymonds** [comment]
@clstokes @davidsbond @knyar 

I've tested this manually, but not sure how easy or useful it is to add a unit test.

**Comment by knyar** [comment]
Thank you! I might be missing something, but what does this achieve if validation is only called immediately before attempting to set ACL contents with the same value? The same validation (including tests) will be applied while ACL content is [being set](https://github.com/tailscale/tailscale/blob/main/api.md#update-policy-file), and an error should be returned if any of the tests fail.

**Comment by dsymonds** [comment]
That's a good point! For some reason I thought this wasn't happening, but just tested it manually now and the tests do indeed get exercised.

Okay, let me pare this right back to just the documentation update.

**Comment by dsymonds** [comment]
PTAL @knyar

**Comment by dsymonds** [comment]
Ah ha! I overlooked the very subtle "generated" comment at the top. Done properly now.

PTAL @knyar

**Review by knyar — APPROVED** [review]
Thank you!

**Pull request merged**
